project(
    'celaratcp',
    'cpp',
    version: '0.0.1',
    license: 'AGPL-3.0-or-later',
    meson_version: '>=1.2.0',
    default_options : [
        'cpp_std=c++20',
        'warning_level=2',
        'c_std=c11',
    ]
)

celaratcp_com_inc = include_directories('common/inc')

subdir('netio')
